name: "Coswarm Deploy"
description: "Trigger the Coswarm deployment API with a Docker image reference."
author: "Coswarm"
inputs:
  token:
    description: "API token with permission to deploy the app."
    required: true
  image:
    description: "Container image tag to deploy. Example: redis:alpine"
    required: true
  base-url:
    description: "Coswarm API base URL. Must be provided explicitly."
    required: true
  github-token:
    description: "Personal access token to create an issue when the deploy fails. Defaults to GITHUB_TOKEN."
    required: false
outputs:
  response:
    description: "Raw response body returned by the Coswarm API."
runs:
  using: "node20"
  main: "build/index.js"
branding:
  icon: "cloud"
  color: "blue"
