name: "Coswarm Deploy"
description: "Trigger the Coswarm deployment API with a Docker image reference."
author: "Coswarm"
inputs:
  token:
    description: "API token with permission to deploy the app."
    required: true
  image:
    description: "Container image tag to deploy. Example: redis:alpine"
    required: true
  base-url:
    description: "Coswarm API base URL. Must be provided explicitly."
    required: true
  github-token:
    description: "GitHub token used to create issues/comments and update releases. Defaults to GITHUB_TOKEN.\n\nIf you rely on the default GITHUB_TOKEN, ensure the calling workflow grants the action write permissions (for example `contents: write` and `issues: write`). For workflows triggered from forks, secrets and write permissions may be unavailable — in that case provide a Personal Access Token (PAT) via this input with minimal required scopes (e.g. `repo`/`public_repo`)."
    required: false
outputs:
  response:
    description: "Raw response body returned by the Coswarm API."
runs:
  using: "node20"
  main: "build/index.js"
branding:
  icon: "cloud"
  color: "blue"
