name: "Coswarm Deploy"
description: "Trigger the Coswarm deployment API with a Docker image reference."
author: "Coswarm"
inputs:
  token:
    description: "API token with permission to deploy the app."
    required: true
  image:
    description: "Container image tag to deploy. Example: redis:alpine"
    required: true
  base-url:
    description: "Coswarm API base URL. Must be provided explicitly."
    required: true
runs:
  using: "composite"
  steps:
    - id: deploy
      shell: bash
      run: |
        set -euo pipefail
        BASE_URL="${{ inputs.base-url }}"
        if [[ -z "${BASE_URL}" ]]; then
          echo "Error: inputs.base-url must be set." >&2
          exit 1
        fi
        # Ensure the URL has no trailing slash before appending the endpoint
        API_URL="${BASE_URL%%/}/api/v1/apps/deploy"
        echo "Triggering deploy via ${API_URL}"
        curl -sS -L "${API_URL}" \
          -H 'Content-Type: application/json' \
          -d "$(jq -n --arg token "${{ inputs.token }}" --arg image "${{ inputs.image }}" '{token:$token,image:$image}')"
branding:
  icon: "cloud"
  color: "blue"
